services:

    #
    # Form Types

    PayumPostFinanceFlexBundle\Form\Payment\PostFinanceFlexType:
        tags:
            - { name: coreshop.gateway_configuration_type, type: postfinance_flex }
            - { name: form.type }

    #
    # Payum Factories

    payum.postfinance_flex_gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [DachcomDigital\Payum\PostFinance\Flex\PostFinanceFlexGatewayFactory]
        tags:
            - {name: payum.gateway_factory_builder, factory: postfinance_flex }

    #
    # Payum Extensions

    PayumPostFinanceFlexBundle\Extension\ConvertPaymentExtension:
        autowire: true
        public: true
        arguments:
            - '@coreshop.repository.payment'
        tags:
            - { name: payum.extension, alias: postfinance_flex_coreshop_convert_payment, factory: postfinance_flex, prepend: false }
